default_install_hook_types: [pre-commit]
repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: npm run lint
        language: node
        always_run: true
        require_serial: true
      - id: build
        name: build
        entry: npm run build
        language: node
        always_run: true
        require_serial: true